export const APP_LOGIN_AUTHENTICATION_SUCCESS =
  "app.reducer/APP_LOGIN_AUTHENTICATION_SUCCESS";
export const APP_LOGIN_AUTHENTICATION_FAILED =
  "app.reducer/APP_LOGIN_AUTHENTICATION_FAILED";
export const GET_APP_LOCAL_STORE_DATA = "app.reducer/GET_APP_LOCAL_STORE_DATA";

export const APP_LOGOUT_ACTION = "app.reducer/APP_LOGOUT_ACTION";
