export const COMPONENTS_CREATE_ACCOUNT_SUCCESS =
  'COMPONENTS_CREATE_ACCOUNT_SUCCESS';
export const COMPONENTS_CREATE_ACCOUNT_FAILED =
  'COMPONENTS_CREATE_ACCOUNT_FAILED';

export const COMPONENTS_AUTHENTICATE_USER_SUCCESS =
  'COMPONENTS_AUTHENTICATE_USER_SUCCESS';
export const COMPONENTS_AUTHENTICATE_USER_FAILED =
  'COMPONENTS_AUTHENTICATE_USER_FAILED';

export const COMPONENTS_RETRIEVE_PASSWORD_SUCCESS =
  'COMPONENTS_RETRIEVE_PASSWORD_SUCCESS';
export const COMPONENTS_RETRIEVE_PASSWORD_FAILED =
  'COMPONENTS_RETRIEVE_PASSWORD_FAILED';

export const COMPONENTS_RESET_PASSWORD_SUCCESS =
  'COMPONENTS_RESET_PASSWORD_SUCCESS';
export const COMPONENTS_RESET_PASSWORD_FAILED =
  'COMPONENTS_RESET_PASSWORD_FAILED';

export const COMPONENTS_UPDATE_PROFILE_SUCCESS =
  'COMPONENTS_UPDATE_PROFILE_SUCCESS';
export const COMPONENTS_UPDATE_PROFILE_FAILED =
  'COMPONENTS_UPDATE_PROFILE_FAILED';
