export const COMPONENTS_WARNING_LIST_SUCCESS =
  'COMPONENTS_WARNING_LIST_SUCCESS';
export const COMPONENTS_WARNING_LIST_FAILED =
  'COMPONENTS_WARNING_LIST_FAILED';

export const COMPONENTS_READ_UNREAD_SUCCESS =
  'COMPONENTS_READ_UNREAD_SUCCESS';
export const COMPONENTS_READ_UNREAD_FAILED =
  'COMPONENTS_READ_UNREAD_FAILED';

  export const COMPONENTS_MARK_ALL_READ_SUCCESS = 
  'COMPONENTS_MARK_ALL_READ_SUCCESS';

  export const COMPONENTS_MARK_ALL_READ_FAILED = 
  'COMPONENTS_MARK_ALL_READ_FAILED';
