export const COMPONENTS_NOTIFICATION_COUNT_SUCCESS =
  'COMPONENTS_NOTIFICATION_COUNT_SUCCESS';
export const COMPONENTS_NOTIFICATION_COUNT_FAILED =
  'COMPONENTS_NOTIFICATION_COUNT_FAILED';

export const COMPONENTS_FCM_TOKEN_SUCCESS =
  'COMPONENTS_FCM_TOKEN_SUCCESS';
export const COMPONENTS_FCM_TOKEN_FAILED =
  'COMPONENTS_FCM_TOKEN_FAILED';

  export const COMPONENTS_GET_COUNT_SUCCESS =
  'COMPONENTS_GET_COUNT_SUCCESS';
export const COMPONENTS_GET_COUNT_FAILED =
  'COMPONENTS_GET_COUNT_FAILED';
